# AlertManager configuration file

global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX'

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-warnings'
      continue: true
    - match:
        severity: info
      receiver: 'slack-notifications'

receivers:
  - name: 'slack-critical'
    slack_configs:
      - channel: '#alerts-critical'
        send_resolved: true
        icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        text: >-
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}{{ if .Annotations.description }}
          *Description:* {{ .Annotations.description }}{{ end }}
          *Severity:* {{ .Labels.severity }}
          *Environment:* {{ .Labels.environment }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'https://grafana.yourtradingapp.com/d/{{ .CommonLabels.dashboard_id }}'
          - type: button
            text: 'View in Prometheus'
            url: 'https://prometheus.yourtradingapp.com/alerts'

  - name: 'slack-warnings'
    slack_configs:
      - channel: '#alerts-warnings'
        send_resolved: true
        icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        text: >-
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}{{ if .Annotations.description }}
          *Description:* {{ .Annotations.description }}{{ end }}
          *Severity:* {{ .Labels.severity }}
          *Environment:* {{ .Labels.environment }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'https://grafana.yourtradingapp.com/d/{{ .CommonLabels.dashboard_id }}'
          - type: button
            text: 'View in Prometheus'
            url: 'https://prometheus.yourtradingapp.com/alerts'

  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts-info'
        send_resolved: true
        icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        text: >-
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}{{ if .Annotations.description }}
          *Description:* {{ .Annotations.description }}{{ end }}
          *Severity:* {{ .Labels.severity }}
          *Environment:* {{ .Labels.environment }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'https://grafana.yourtradingapp.com/d/{{ .CommonLabels.dashboard_id }}'
          - type: button
            text: 'View in Prometheus'
            url: 'https://prometheus.yourtradingapp.com/alerts'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
