# Prometheus configuration file

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/node_exporter_rules.yml"
  - "rules/container_rules.yml"
  - "rules/application_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Frontend application metrics
  - job_name: 'frontend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['frontend:3000']

  # Backend API metrics
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8080']

  # Rust services metrics
  - job_name: 'rust-services'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rust-services:8081', 'rust-services:8082']

  # C++ components metrics
  - job_name: 'cpp-components'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cpp-components:8083', 'cpp-components:8084']
